### ISSUE TITLE
Fonts don't seem to work in the browser (preloadRemoteFonts)

### ISSUE THREAD

**Issue by WojciechP** [Myriad-Dreamin/typst.ts#605] opened 2024-11-23 19:23 UTC
**Describe the bug**
I am using typst.ts to generate PDFs in the browser. It works, but I can't figure out how to change fonts. Using `preloadRemoteFonts` causes the browser to actually fetch the woff files, but the rendered PDF doesn't use them.

It is very likely that I'm holding the typst.ts API wrong.

**Reproducer:**
I tried reproducing this in a single file, but I cannot get a single-file thing to work at all; visiting https://myriad-dreamin.github.io/typst.ts/preview.html gives me a JS console error: `Uncaught (in promise) LinkError: import object field '__wbg_call_3bfa248576352471' is not a Function`.

I only managed to reproduce it with a build tool, I chose vite. The reproducer is in https://github.com/WojciechP/typst-fonts-reproducer.
The relevant bit of code:

```ts
import { createTypstCompiler } from "@myriaddreamin/typst.ts/dist/esm/compiler.mjs";
import wasmURL from "@myriaddreamin/typst-ts-web-compiler/pkg/typst_ts_web_compiler_bg.wasm?url";
import { preloadRemoteFonts } from "@myriaddreamin/typst.ts/dist/esm/options.init.mjs";

const cc = createTypstCompiler();
await cc.init({
  getModule: () => {
    return { module_or_path: wasmURL };
  },
  beforeBuild: [
    preloadRemoteFonts([
      "https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2",
      "https://fonts.gstatic.com/s/arimo/v29/P5sfzZCDf9_T_3cV7NCUECyoxNk37cxcABrHdwcoaaQw.woff",
    ]),
  ],
});
const lines = [
  "Some text using the default font \\",
  '#set text(font: "Roboto")',
  "Some text using Roboto font",
];
const source = lines.join("\n");

cc.addSource("/main.typ", source);

document.querySelector("#source")!.textContent = source;

const result = await cc.compile({
  format: "pdf",
  mainFilePath: "/main.typ",
  diagnostics: "full",
});
console.log(result.diagnostics);
if (result.result) {
  const blob = new Blob([result.result!], { type: "application/pdf" });
  const link = document.querySelector<HTMLAnchorElement>("#pdf")!;
  link.href = window.URL.createObjectURL(blob);
  link.textContent = "Download PDF";
  link.download = "main.pdf";
}
```

I would expect the two lines in the resulting PDF to render differently, but they don't. There are no diagnostics returned.

My understanding is that Typst has a font fallback, so when it cannot find a font it uses whatever's available. Passing `fallback: false` to `set text` causes the second line to disappear entirely.

**Expected behavior**
The second line should use Roboto.

**Desktop (please complete the following information):**
 OSX, Firefox 132.0.1

**Package/Software version (using command `typst-ts-cli --VV full` and paste down the output):**

I am not using the CLI at all, I am only importing the typst-ts in TypeScript. The relevant bit of my package.json:

```
 "devDependencies": {
    "typescript": "~5.6.2",
    "vite": "^5.4.10"
  },
  "dependencies": {
    "@myriaddreamin/typst-ts-web-compiler": "^0.5.0-rc9",
    "@myriaddreamin/typst.ts": "^0.5.0-rc9"
  }
```

Any help or suggestions on how to troubleshoot further would help. Alternatively, any demo that uses multiple fonts would probably help too, but I couldn't find one. Thank you in advance!

**Comment by Myriad-Dreamin** [comment] 2024-11-26 08:36
> visiting https://myriad-dreamin.github.io/typst.ts/preview.html gives me a JS console error: Uncaught (in promise) LinkError: import object field '__wbg_call_3bfa248576352471' is not a Function.

Yeah, I see it is broken. I'll try to fix it.

> ```js
>  preloadRemoteFonts([
>       "https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2",
>       "https://fonts.gstatic.com/s/arimo/v29/P5sfzZCDf9_T_3cV7NCUECyoxNk37cxcABrHdwcoaaQw.woff",
>     ]),
> ```

Probably a same issue as https://github.com/Myriad-Dreamin/typst.ts/issues/600#issuecomment-2499978278.

> Hello hat618 your woff2 font seems not being identified by typst correctly. I know it by downloading fonts and check it offline:
> 
> ```
> typst fonts --font-path Downloads 
> ```
> 
> And "Roboto" font is not in the identified list of fonts.
> 
> To confirm it, I used the roboto fonts on Google Fonts from the [gist](https://gist.github.com/karimnaaji/b6c9c9e819204113e9cabf290d580551) and everything works as expected:
> 
> ```js
> $typst.setCompilerInitOptions({
>   beforeBuild: [
>     preloadRemoteFonts([
>       'http://fonts.gstatic.com/s/roboto/v15/7MygqTe2zs9YkP0adA9QQQ.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/T1xnudodhcgwXCmZQ490TPesZW2xOQ-xsNqO47m55DA.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/dtpHsbgPEm2lVWciJZ0P-A.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/iE8HhaRzdhPxC93dOdA056CWcynf_cDxXwCLxiixG1c.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/W5F8_SL0XFawnjxHGsZjJA.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/hcKoSgxdnKlbH5dlTwKbow.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/Uxzkqj-MIMWle-XP2pDNAA.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/daIfzbEw-lbjMyv4rMUUTqCWcynf_cDxXwCLxiixG1c.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/bdHGHleUa-ndQCOrdpfxfw.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/owYYXKukxFDFjr0ZO8NXh6CWcynf_cDxXwCLxiixG1c.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/H1vB34nOKWXqzKotq25pcg.ttf',
>       'http://fonts.gstatic.com/s/roboto/v15/b9PWBSMHrT2zM5FgUdtu0aCWcynf_cDxXwCLxiixG1c.ttf',
>     ]),
>   ],
> });
> ```

**Comment by WojciechP** [comment] 2024-11-26 18:50
Thank you for a speedy answer! Indeed using the .toff fonts from the linked gists instead of the .woff files solves the issue. Feel free to mark this as duplicate of https://github.com/Myriad-Dreamin/typst.ts/issues/600, I don't know why I hadn't found it myself.

**Comment by Myriad-Dreamin** [comment] 2024-11-26 21:52
Duplicate of #600

**Closed by Myriad-Dreamin** 2024-11-26 21:52 UTC
